/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.quizif.view;

import br.edu.ifnmg.quizif.model.Questao;
import java.awt.Color;

/**
 *
 * @author danilo
 */
public class PainelQuizFrm extends javax.swing.JFrame {

    private Questao questaoSelecionada = null;
    private Integer tempo = null;
    /**
     * Creates new form PainelQuizFrm
     */
    public PainelQuizFrm() {
        initComponents();
        limpaTela();
        pbTempo.setVisible(false);
    }
    
    public void definirTempoMaximo(int tempo){
        this.tempo = tempo*1000;
        pbTempo.setMaximum(this.tempo);
        pbTempo.setValue(this.tempo);
        pbTempo.setVisible(true);
    }
    
    public void atualizarTempo(int tempo){
        this.tempo = tempo;
        pbTempo.setValue(this.tempo);
        pbTempo.repaint();
    }
    
    public void setQuestaoSelecionada(Questao questaoSelecionada) {
        this.questaoSelecionada = questaoSelecionada;
        atualizaTela();
    }
    public boolean isProjetandoQuestao(){
        return questaoSelecionada != null;
    }
    public void resetRespostaSelecionada(){
        lblResposta1.setBackground(new Color(83,168,254));
        lblResposta2.setBackground(new Color(83,168,254));
        lblResposta3.setBackground(new Color(83,168,254));
        lblResposta4.setBackground(new Color(83,168,254));
    }
    public void selecionarResposta(Integer resposta){
        resetRespostaSelecionada();
        if(resposta == null){
            return;
        }
        switch (resposta) {
            case 1:
                lblResposta1.setBackground(Color.GREEN);
                break;
            case 2:
                lblResposta2.setBackground(Color.GREEN);
                break;
            case 3:
                lblResposta3.setBackground(Color.GREEN);
                break;
            case 4:
                lblResposta4.setBackground(Color.GREEN);
                break;
            default:
                throw new AssertionError();
        }
    }
    private void limpaTela(){
        lblQuestao.setText("");
        lblResposta1.setText("");
        lblResposta2.setText("");
        lblResposta3.setText("");
        lblResposta4.setText("");
    }
    
    private void atualizaTela(){
        StringBuilder textoQuestao = new StringBuilder();
        textoQuestao.append("<html><p \\\"line-height:1\\\" align=\\\"JUSTIFY\\\"><b>");
        textoQuestao.append(questaoSelecionada.getTexto());
        textoQuestao.append("</b></p></html>");
        lblQuestao.setText(textoQuestao.toString());
        lblResposta1.setText("<html><p \\\"line-height:1\\\" align=\\\"JUSTIFY\\\"><b>A) "+questaoSelecionada.getResposta1()+"</b></p></html>");
        lblResposta2.setText("<html><p \\\"line-height:1\\\" align=\\\"JUSTIFY\\\"><b>B) "+questaoSelecionada.getResposta2()+"</b></p></html>");
        lblResposta3.setText("<html><p \\\"line-height:1\\\" align=\\\"JUSTIFY\\\"><b>C) "+questaoSelecionada.getResposta3()+"</b></p></html>");
        lblResposta4.setText("<html><p \\\"line-height:1\\\" align=\\\"JUSTIFY\\\"><b>D) "+questaoSelecionada.getResposta4()+"</b></p></html>");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblQuestao = new javax.swing.JLabel();
        lblResposta2 = new javax.swing.JLabel();
        lblResposta1 = new javax.swing.JLabel();
        lblResposta3 = new javax.swing.JLabel();
        lblResposta4 = new javax.swing.JLabel();
        pbTempo = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(217, 255, 111));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quiz IF");

        lblQuestao.setBackground(new java.awt.Color(42, 148, 254));
        lblQuestao.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblQuestao.setText("<html><p \\\"line-height:1\\\" align=\\\"JUSTIFY\\\">Qual a cor do cavalo brando de napoleão?<b><font size=\\\"70px\\\">João</font></b></p></html>");
        lblQuestao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblQuestao.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        lblQuestao.setOpaque(true);

        lblResposta2.setBackground(new java.awt.Color(83, 168, 254));
        lblResposta2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblResposta2.setText("jLabel2");
        lblResposta2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblResposta2.setOpaque(true);

        lblResposta1.setBackground(new java.awt.Color(83, 168, 254));
        lblResposta1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblResposta1.setText("jLabel2");
        lblResposta1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblResposta1.setOpaque(true);

        lblResposta3.setBackground(new java.awt.Color(83, 168, 254));
        lblResposta3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblResposta3.setText("jLabel2");
        lblResposta3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblResposta3.setOpaque(true);

        lblResposta4.setBackground(new java.awt.Color(83, 168, 254));
        lblResposta4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblResposta4.setText("jLabel2");
        lblResposta4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblResposta4.setOpaque(true);

        pbTempo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        pbTempo.setValue(50);
        pbTempo.setString("Tempo Restante (5s)");
        pbTempo.setStringPainted(true);

        jPanel1.setBackground(new java.awt.Color(217, 255, 111));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(217, 255, 111));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(254, 177, 26));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResposta3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResposta2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResposta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQuestao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblResposta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblQuestao, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addGap(22, 22, 22)
                .addComponent(pbTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblResposta1, lblResposta2, lblResposta3, lblResposta4});

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblQuestao;
    private javax.swing.JLabel lblResposta1;
    private javax.swing.JLabel lblResposta2;
    private javax.swing.JLabel lblResposta3;
    private javax.swing.JLabel lblResposta4;
    private javax.swing.JProgressBar pbTempo;
    // End of variables declaration//GEN-END:variables
}
